"""Authoritative schema for the Priority Google Sheet."""

from __future__ import annotations

SHEET_TAB_DEFAULT = "Priorities"

# Column order matters — this is the exact left-to-right layout written to Google Sheets.
COLUMNS: list[dict] = [
    {
        "name": "Task_ID",
        "type": "string",
        "required": True,
        "description": "Unique identifier. Format: T-NNN (e.g. T-001). Subtasks append a letter: T-001a.",
        "example": "T-001",
    },
    {
        "name": "Parent_ID",
        "type": "string",
        "required": False,
        "description": "Task_ID of the parent task. Empty for top-level priorities.",
        "example": "T-001",
    },
    {
        "name": "Task_Name",
        "type": "string",
        "required": True,
        "description": "Action-oriented title. Should complete the sentence: 'I need to...'",
        "example": "Set up OAuth credentials for marketing analytics pipeline",
    },
    {
        "name": "Category",
        "type": "string",
        "required": False,
        "description": "Domain label for filtering and reporting.",
        "example": "Professional | Personal | Health | Financial | Relationship | Creative | Administrative",
    },
    {
        "name": "Value_Score",
        "type": "fibonacci",
        "required": True,
        "description": "Direct economic or personal benefit. Fibonacci scale: 1,2,3,5,8,13,20,40,100.",
        "example": 5,
    },
    {
        "name": "Time_Criticality",
        "type": "fibonacci",
        "required": True,
        "description": "Speed of value decay if delayed. High = hard deadline or closing window.",
        "example": 3,
    },
    {
        "name": "RR_OE_Score",
        "type": "fibonacci",
        "required": True,
        "description": "Risk Reduction / Opportunity Enablement. High = unblocks many successors.",
        "example": 8,
    },
    {
        "name": "Job_Size",
        "type": "fibonacci",
        "required": True,
        "description": "Effort + complexity + duration. >= 13 triggers decomposition.",
        "example": 3,
    },
    {
        "name": "Base_WSJF",
        "type": "float",
        "required": False,
        "description": "Auto-calculated: (Value + Time_Criticality + RR_OE) / Job_Size.",
        "formula": "=(E{row}+F{row}+G{row})/H{row}",
        "example": 5.33,
    },
    {
        "name": "Predecessor_IDs",
        "type": "string",
        "required": False,
        "description": "Comma-separated Task_IDs that must complete before this task can start.",
        "example": "T-001, T-003",
    },
    {
        "name": "Successor_IDs",
        "type": "string",
        "required": False,
        "description": "Comma-separated Task_IDs currently blocked by this task. Auto-populated by dependency-detective.",
        "example": "T-007, T-008",
    },
    {
        "name": "Adjusted_WSJF",
        "type": "float",
        "required": False,
        "description": "AI-calculated: Base_WSJF + 0.5 × sum of all downstream Base_WSJFs. This is the sequencing field.",
        "example": 12.7,
    },
    {
        "name": "Bottleneck_Score",
        "type": "integer",
        "required": False,
        "description": "Frequency × Impact × Solvability (each 1–5). > 50 triggers priority inflation.",
        "example": 60,
    },
    {
        "name": "Duration_Days",
        "type": "integer",
        "required": False,
        "description": "Estimated calendar days to complete. Used for cascading schedule calculation.",
        "example": 3,
    },
    {
        "name": "Task_Start_Date",
        "type": "date",
        "required": False,
        "description": "Earliest possible start: max(end dates of all predecessors). Set by analysis engine.",
        "example": "2026-05-25",
    },
    {
        "name": "Task_End_Date",
        "type": "date",
        "required": False,
        "description": "Task_Start_Date + Duration_Days.",
        "example": "2026-05-28",
    },
    {
        "name": "Status",
        "type": "categorical",
        "required": True,
        "description": "Execution state.",
        "allowed_values": ["Backlog", "In Progress", "Blocked", "Completed", "Deferred"],
        "example": "Backlog",
    },
    {
        "name": "Priority_Rank",
        "type": "integer",
        "required": False,
        "description": "Final sequenced rank (1 = do first). Set by the analysis engine.",
        "example": 1,
    },
    {
        "name": "Pros",
        "type": "string",
        "required": False,
        "description": "Pipe-separated pros generated by evaluation-agent.",
        "example": "Unblocks Q3 pipeline | Reduces 10h/week manual effort",
    },
    {
        "name": "Cons",
        "type": "string",
        "required": False,
        "description": "Pipe-separated cons generated by evaluation-agent.",
        "example": "Requires coordination with 2 teams | Delays T-009 by 1 week",
    },
    {
        "name": "Notes",
        "type": "string",
        "required": False,
        "description": "Free-form context, dependencies to investigate, or risk flags.",
        "example": "Check with legal before starting.",
    },
    {
        "name": "Last_Updated",
        "type": "date",
        "required": False,
        "description": "Timestamp of last modification. Auto-set by the CLI.",
        "example": "2026-05-22",
    },
]

COLUMN_NAMES: list[str] = [c["name"] for c in COLUMNS]
COLUMN_INDEX: dict[str, int] = {c["name"]: i for i, c in enumerate(COLUMNS)}

FIBONACCI_SCALE = {1, 2, 3, 5, 8, 13, 20, 40, 100}
STATUS_VALUES = {"Backlog", "In Progress", "Blocked", "Completed", "Deferred"}
FIBONACCI_FIELDS = {"Value_Score", "Time_Criticality", "RR_OE_Score", "Job_Size"}


def validate_row(row: dict) -> list[str]:
    """Return a list of validation error strings. Empty list = valid."""
    errors: list[str] = []

    if not row.get("Task_ID"):
        errors.append("Task_ID is required")

    if not row.get("Task_Name"):
        errors.append("Task_Name is required")

    for field in FIBONACCI_FIELDS:
        val = row.get(field)
        if val is not None and val != "":
            try:
                if int(val) not in FIBONACCI_SCALE:
                    errors.append(f"{field}={val} is not a valid Fibonacci scale value")
            except (ValueError, TypeError):
                errors.append(f"{field}={val} is not a valid integer")

    status = row.get("Status")
    if status and status not in STATUS_VALUES:
        errors.append(f"Status='{status}' is not valid. Must be one of: {', '.join(sorted(STATUS_VALUES))}")

    return errors


def row_to_dict(values: list) -> dict:
    """Convert a flat list of cell values (in column order) to a named dict."""
    result = {}
    for i, col in enumerate(COLUMNS):
        result[col["name"]] = values[i] if i < len(values) else ""
    return result


def dict_to_row(data: dict) -> list:
    """Convert a named dict to a flat list in column order for sheet writing."""
    return [data.get(col["name"], "") for col in COLUMNS]


def get_column_letter(field_name: str) -> str:
    """Return the A1 column letter for a field name (A=0, B=1, ...)."""
    idx = COLUMN_INDEX.get(field_name)
    if idx is None:
        raise KeyError(f"Unknown field: {field_name}")
    # Simple A-Z then AA-AZ
    if idx < 26:
        return chr(ord("A") + idx)
    return chr(ord("A") + idx // 26 - 1) + chr(ord("A") + idx % 26)
